### GET ALL ADS
GET {{base_url}}/ads

### ADD A NEW AD
POST {{base_url}}/ads
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

{
    "title":"Ad Title",
    "body": "Ad body",
    "image": "https://www.example.com/images/sample.jpg",
    "startDate": "2023-12-11T16:36:06.839Z",
    "endDate": "2023-12-15T16:36:06.839Z",
    "price": 500,
    "duration": "5"
}