### GET ALL ADS
GET {{base_url}}/ads

### ADD A NEW AD
POST {{base_url}}/ads
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

{
    "title":"Ad Title",
    "body": "Ad body",
    "image": "https://www.example.com/images/sample.jpg",
    "startDate": "2023-12-12T16:36:06.839Z",
    "endDate": "2023-12-15T16:36:06.839Z",
    "price": 500,
    "duration": "5"
}

### PAYMENT INIT
POST {{base_url}}/ads/paymentInit
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

{
    "price": 500,
    "currency": "usd"
}

### DELETE THE AD
DELETE {{base_url}}/ads/{{ad_id}}
Content-Type: {{content_type}}
Authorization: {{authorization_token}}