### REGISTER
POST {{base_url}}/auth/register
Content-Type: {{content_type}}

{
	"firstName": "{{firstName}}",
	"lastName": "{{lastName}}",
	"email": "{{email}}",
	"password": "{{password}}"
}

### LOGIN
POST {{base_url}}/auth/login
Content-Type: {{content_type}}

{
  "email": "ilic.bojan.bi@gmail.com",
  "password": "Bojan123"
}


