### GET ALL MESSAGES (both public and private for authenticated user)
GET {{base_url}}/messages
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

### FETCH PRIVATE MESSAGES BETWEEN LOGGED-IN USER AND ANOTHER SPECIFIED USER
GET {{base_url}}/messages/private/{{receiver_id}}
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

### ADD A PRIVATE MESSAGE
POST {{base_url}}/messages/addMessage/{{receiver_id}}
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

{
    "message": "This is a private message!",
    "isPublic": false
}

### ADD A PUBLIC MESSAGE
POST {{base_url}}/messages/addMessage
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

{
    "message": "This is a public message!",
    "isPublic": true
}