### GET ALL POSTS
GET {{base_url}}/posts/all

### GET ALL POSTS (Paginated and Filtered by Public Status)
GET {{base_url}}/posts/all?page=1&limit=2&public=1

### GET POST BY ID
GET {{base_url}}/posts/{{post_id}}

### GET POST BY TAGS
GET {{base_url}}/posts/filter?tags=magical&tags=classic

### SEARCH POST
GET {{base_url}}/posts/search?searchQuery=magical

### ADD POST
POST {{base_url}}/posts/add
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

{
    "body": "Post body content",
    "title": "Post title content",
    "image": "https://www.example.com/images/sample.jpg",
    "isPublic": false,
    "tags": [
        {
            "name": "tag1"
        },
		{
			"name": "tag2"
		},
		{
			"name": "tag3"
		}
    ]
}

### DELETE THE POST
DELETE {{base_url}}/posts/{{post_id}}
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

### UPDATE POST BY ID
PUT {{base_url}}/posts/{{post_id}}
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

{
    "body": "Updated Post body content",
    "title": "Updated Post Title",
    "image": "https://example.com/updated-image.jpg",
    "isPublic": true,
    "tags": [
        {
            "name": "tag1updated"
        },
        {
            "name": "tag2updated"
        }
    ]
}




