### GET ALL POSTS
GET {{base_url}}/posts/all

### GET ALL POSTS (Paginated and Filtered by Public Status)
GET {{base_url}}/posts/all?page=1&limit=2&public=1

### ADD POST
POST {{base_url}}/posts/add
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

{
    "body": "Post body content",
    "title": "Post title content",
    "image": "https://www.example.com/images/sample.jpg",
    "isPublic": false,
    "tags": [
        {
            "name": "Tag 1"
        },
		{
			"name": "Tag 2"
		},
		{
			"name": "Tag 3"
		}
    ]
}

### DELETE THE POST
DELETE {{base_url}}/posts/{{post_id}}
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

### UPDATE POST BY ID
PUT {{base_url}}/posts/{{post_id}}
Content-Type: {{content_type}}
Authorization: {{authorization_token}}

{
    "body": "Updated Post body content",
    "title": "Updated Post Title",
    "image": "https://example.com/updated-image.jpg",
    "isPublic": true,
    "tags": [
        {
            "name": "Tag 1 Updated"
        },
        {
            "name": "Tag 2 Updated"
        }
    ]
}




